services:
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
        container_name: elasticsearch
        restart: unless-stopped
        mem_limit: 4g
        cpus: 2
        environment:
          - discovery.type=single-node                  # single-node cluster
          - xpack.security.enabled=true                 # disable password security
          - xpack.security.http.ssl.enabled=false       # disable tls/ssl encryption
          - xpack.security.transport.ssl.enabled=false  # disable tls/ssl encryption
          - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
          - ELASTIC_PASSWORD=Qy3uacBChz82ErxlHMzE        # 设置 elasticsearch 用户的密码
        ports:
          - 9200:9200
        volumes:
          # sudo chown -R 1000:1000 ./elasticsearch
          - ./elasticsearch:/usr/share/elasticsearch/data
        networks:
          - local
        depends_on:
          - fluent-bit
    kibana:
        image: docker.elastic.co/kibana/kibana:8.13.4
        container_name: kibana
        restart: unless-stopped
        mem_limit: 1g
        cpus: 1
        environment:
          - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
          - SERVER_HEAP_SIZE=512mm
          - DISABLE_OBSERVABILITY=true  # 禁用 Observability 插件
          - ELASTICSEARCH_USERNAME=kibana  # 设置 Kibana 使用的 Elasticsearch 用户名
          - ELASTICSEARCH_PASSWORD=BtXtm9Z83tGl6iM1VDDn # 设置 Kibana 的密码，需与 Elasticsearch 密码匹配
          - NODE_OPTIONS=--openssl-legacy-provider
        ports:
          - 5601:5601
        networks:
          - local
        depends_on:
          - fluent-bit
          - elasticsearch
    fluent-bit:
        image: fluent/fluent-bit:4.0
        container_name: fluent-bit
        mem_limit: 1g
        cpus: 1
        restart: unless-stopped
        command:
          - /fluent-bit/bin/fluent-bit
          - --config=/etc/fluent-bit/fluent-bit.conf
        environment:
          - FLB_ES_HOST=elasticsearch
          - FLB_ES_PORT=9200
        ports:
          #- 2020:2020
          - 24224:24224
        volumes:
          - ./conf/:/etc/fluent-bit/:ro
          - /igs-server:/igs-server
          - ./fluent-bit:/var/log/fluent-bit
        networks:
          - local

networks:
  local:
    driver: bridge
